# fly.toml file generated for anecdotes on 2022-11-02T11:17:47+02:00

app = "anecdotes"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "npm run build"

[processes]
  app = "npm run serve_front"
  db = "npm run server"


[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = [3001]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app", "db"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 3001

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  
  

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
